from collections.abc import Sequence
from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol

from requiem.modules.moderation.domain import Authority, Message, TemporaryBan


class DiscordModeration(Protocol):
    async def authority(
        self,
        guild_id: int,
        actor_id: int,
        target_id: int | None = None,
        channel_id: int | None = None,
    ) -> Authority: ...
    async def warn_dm(self, user_id: int, guild_name: str, reason: str) -> bool: ...
    async def timeout(
        self, guild_id: int, user_id: int, until: datetime | None, reason: str | None
    ) -> None: ...
    async def kick(self, guild_id: int, user_id: int, reason: str | None) -> None: ...
    async def ban(
        self, guild_id: int, user_id: int, delete_seconds: int, reason: str | None
    ) -> None: ...
    async def is_banned(self, guild_id: int, user_id: int) -> bool: ...
    async def unban(self, guild_id: int, user_id: int, reason: str | None) -> None: ...
    async def messages(self, channel_id: int, before: int | None) -> Sequence[Message]: ...
    async def delete(
        self, channel_id: int, messages: Sequence[int], reason: str | None
    ) -> None: ...


class BanStore(Protocol):
    def lock(self, guild_id: int, user_id: int) -> AbstractAsyncContextManager[None]: ...
    async def save(self, ban: TemporaryBan) -> None: ...
    async def get(self, guild_id: int, user_id: int) -> TemporaryBan | None: ...
    async def remove(self, guild_id: int, user_id: int) -> None: ...
    async def due(self, now: datetime) -> Sequence[TemporaryBan]: ...
    async def defer(self, guild_id: int, user_id: int, until: datetime) -> None: ...
